Repository EotvosCollegium/mars, pull requests merged in 2022-10, with the labels that each got.

#148 Fix loading the community services
  app/Http/Controllers/StudentsCouncil/CommunityServiceController.php
  app/Providers/AppServiceProvider.php
Labels: bug

#142 Improve tenant handling
  app/Http/Controllers/Auth/ApplicationController.php
  app/Http/Controllers/Auth/RegisterController.php
  app/Http/Controllers/Secretariat/RegistrationsController.php
  app/Http/Controllers/Secretariat/UserController.php
  app/Http/Middleware/PossibleRedirects.php
  app/Models/PersonalInformation.php
  app/Models/User.php
  composer.lock
  resources/lang/en/user.php
  resources/lang/hu/user.php
  resources/views/user/personal-information.blade.php
  resources/views/user/update_tenant_status.blade.php
  routes/web.php
Labels: priority

#155 Restructured and documented the User model
  app/Models/User.php
  app/Utils/CheckoutHandler.php
  resources/views/utils/checkout/all-gathered-transactions.blade.php
Labels: documentation
