Repository EotvosCollegium/mars, pull requests merged in 2024-07, with the labels that each got.

#562 Fixing some security vulnerabilities
  app/Http/Controllers/Secretariat/UserController.php
  app/Utils/CheckoutHandler.php
  app/Utils/LatexSanitizer.php
  resources/views/latex/import.blade.php
  resources/views/latex/register-statement.blade.php
  resources/views/latex/status-cert.blade.php
Labels: bug, priority

#570 Fixing erroneous call which caused the tenant update panel to crash
  resources/views/user/update_tenant_status.blade.php
Labels: bug, priority

#571 Fixing permission problems with applications
  app/Http/Controllers/Auth/ApplicationController.php
  resources/views/auth/application/application.blade.php
  resources/views/auth/application/applications.blade.php
  resources/views/auth/application/status.blade.php
Labels: bug

#564 Fixing checkbox not remembering its previous state; as well as too short question titles
  resources/views/components/input/checkbox.blade.php
  resources/views/secretariat/evaluation-form/anonymous_questions.blade.php
  resources/views/utils/question_card.blade.php
Labels: bug

#577 Last-minute fixes to application process
  app/Http/Controllers/Auth/AdmissionController.php
  app/Http/Controllers/Auth/RegisterController.php
  app/Http/Controllers/Secretariat/UserController.php
  app/Policies/ApplicationPolicy.php
  app/Utils/ApplicationHandler.php
  resources/lang/en/validation.php
  resources/lang/hu/validation.php
  resources/views/auth/admission/application.blade.php
  resources/views/auth/application/app.blade.php
  resources/views/auth/application/questions.blade.php
  resources/views/utils/user/profile-picture.blade.php
  routes/web.php
Labels: bug, priority

#578 Inverting the preloader (the splash animation) for dark theme
  resources/views/layouts/app.blade.php
Labels: bug

#597 Making Neptun code nullable for applicants
  app/Exports/ApplicantsExport.php
  app/Exports/UsersSheets/CollegistsExport.php
  app/Exports/UsersSheets/SemesterEvaluationExport.php
  app/Exports/UsersSheets/StatusesExport.php
  app/Http/Controllers/Secretariat/UserController.php
  app/Models/Application.php
  database/migrations/2024_07_24_210108_make_neptun_nullable_for_applicants.php
  resources/lang/hu/user.php
  resources/views/user/educational-information.blade.php
Labels: priority

#598 Adapting tests to new filters (and making them pass)
  app/Http/Controllers/Auth/AdmissionController.php
  tests/Feature/AdmissionTest.php
  tests/Feature/ApplicationTest.php
Labels: bug

#599 Adding configurable file size limit for application attachments
  .env.example
  app/Http/Controllers/Secretariat/UserController.php
  app/Utils/ApplicationHandler.php
  config/custom.php
  config/print.php
  resources/views/auth/application/files.blade.php
  resources/views/user/alfonso-language-exams.blade.php
  resources/views/utils/user/profile-picture.blade.php
Labels: priority

#606 Further improvements on the application form
  app/Http/Controllers/Secretariat/UserController.php
  app/Models/Application.php
  database/migrations/2024_07_29_105857_applications_make_resident_nullable.php
  database/seeders/UsersTableSeeder.php
  resources/views/auth/application/app.blade.php
  resources/views/auth/application/application.blade.php
  resources/views/auth/application/files.blade.php
  resources/views/auth/application/questions.blade.php
  resources/views/user/alfonso-language-exams.blade.php
  routes/web.php
Labels: priority
